[package]
name = "string_util"
description = "Supports a few operations involving strings"
repository = "https://github.com/abdulwahabO/string-util"
license = "MIT"
version = "0.1.0"
authors = ["Adeshina Ogunmodede <abdulwahabogunmodede@gmail.com>"]
edition = "2018"

[dependencies]
